name: CI

# Controls when the workflow will run
on:
  push:
    branches: 
      - main
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pack-dist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: electron-qq

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2  
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
          
      - uses: zach-hill/gha-yarn-node-cache@1.1
        env:
          WORKING_DIR: electron-qq
      
      - name: Yarn install
        run: yarn install

      - name: webpack
        run: yarn build:ci
              
      - name: upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: electron-qq/dist

  build-x86_64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: pack-dist
    defaults:
      run:
        working-directory: electron-qq
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - run: ls

      - uses: zach-hill/gha-yarn-node-cache@1.1
        env:
          WORKING_DIR: electron-qq

      - run: ls

      - name: get dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: electron-qq/dist

      - name: build
        run: npx electron-builder

      - uses: actions/upload-artifact@v2
        name: upload app-x86_64.asar
        with:
          name: app-x86_64.asar
          path: electron-qq/build/linux-unpacked/resources/app.asar

      - uses: actions/upload-artifact@v2
        name: upload tar xz
        with:
          name: x86_64.tar.gz
          path: electron-qq/build/*.tar.xz

      - uses: actions/upload-artifact@v2
        name: upload app image
        with:
          name: x86_64.AppImage
          path: electron-qq/build/*.AppImage

      - uses: actions/upload-artifact@v2
        name: upload rpm
        with:
          name: x86_64.rpm
          path: electron-qq/build/*.rpm

      - uses: actions/upload-artifact@v2
        name: upload deb
        with:
          name: x86_64.deb
          path: electron-qq/build/*.deb


  #build-arm:
    #runs-on: ubuntu-latest
    #needs: pack-dist
    #defaults:
      #run:
        #working-directory: electron-qq

    #steps:
      #- uses: actions/checkout@v2

      #- uses: zach-hill/gha-yarn-node-cache@1.1
        #env:
          #WORKING_DIR: electron-qq

      #- name: get dist
        #uses: actions/download-artifact@v2
        #with:
          #name: dist
          #path: electron-qq/dist

      #- uses: uraimo/run-on-arch-action@v2.1.1
        #name: build using another arch
        #with:
          #arch: aarch64
          #distro: archarm_latest
          #githubToken: ${{ github.token }}
          #dockerRunArgs: |
            #--volume "${PWD}/electron-qq:/build"
          #install: |
            #pacman -Sy --noconfirm yarn python2 python base-devel npm
          #run: |
            #uname -a
            #chmod -R 777 /build
            #cd /build
            #ls
            #useradd -m builduser
            #su builduser -c 'DEBUG=electron-builder npx electron-builder install-app-deps'
            #su builduser -c 'npx electron-builder'


      #- uses: actions/upload-artifact@v2
        #name: upload app-aarch64.asar
        #with:
          #name: app-aarch64.asar
          #path: electron-qq/build/linux-unpacked/resources/app.asar

      #- uses: actions/upload-artifact@v2
        #name: upload tar xz
        #with:
          #name: aarch64.tar.gz
          #path: electron-qq/build/*.tar.xz

      #- uses: actions/upload-artifact@v2
        #name: upload app image
        #with:
          #name: aarch64.AppImage
          #path: electron-qq/build/*.AppImage

      #- uses: actions/upload-artifact@v2
        #name: upload rpm
        #with:
          #name: aarch64.rpm
          #path: electron-qq/build/*.rpm

      #- uses: actions/upload-artifact@v2
        #name: upload deb
        #with:
          #name: aarch64.deb
          #path: electron-qq/build/*.deb
        
